import type { SpeciesId } from '@/config/gameConfig'
import type { SpeciesVisualConfig } from '../rig/types'

export const SPECIES_VISUALS: Record<SpeciesId, SpeciesVisualConfig> = {
  'gatito-mochi': {
    id: 'gatito-mochi',
    ear: 'pointed',
    tail: 'curl',
    headAccessory: 'none',
    snout: 'none',
    faceMarking: 'none',
    appendage: 'none',
    palette: {
      body: '#FFF3E9',
      bodyDark: '#D9B99A',
      belly: '#FFFDF8',
      accent: '#FFC9D6',
    },
  },
  'conejo-nube': {
    id: 'conejo-nube',
    ear: 'floppy',
    tail: 'cloud',
    headAccessory: 'none',
    snout: 'none',
    faceMarking: 'none',
    appendage: 'none',
    palette: {
      body: '#F3E9FF',
      bodyDark: '#C6A9EA',
      belly: '#FFFFFF',
      accent: '#E3C9FF',
    },
  },
  'pollito-pipo': {
    id: 'pollito-pipo',
    ear: 'none',
    tail: 'stub',
    headAccessory: 'feather-tuft',
    snout: 'beak-round',
    faceMarking: 'none',
    appendage: 'none',
    palette: {
      body: '#FFEA9E',
      bodyDark: '#E0B94A',
      belly: '#FFF6D2',
      accent: '#FF9F45',
    },
  },
  'osito-miel': {
    id: 'osito-miel',
    ear: 'round',
    tail: 'stub',
    headAccessory: 'none',
    snout: 'none',
    faceMarking: 'none',
    appendage: 'none',
    palette: {
      body: '#F5C98B',
      bodyDark: '#C98C4A',
      belly: '#FFEACB',
      accent: '#A9653A',
    },
  },
  'zorrito-kiko': {
    id: 'zorrito-kiko',
    ear: 'pointed',
    tail: 'bushy',
    headAccessory: 'none',
    snout: 'none',
    faceMarking: 'cheek-stripes',
    appendage: 'none',
    palette: {
      body: '#FFB37A',
      bodyDark: '#E08A45',
      belly: '#FFF3E0',
      accent: '#E08A45',
    },
  },
  'panda-bao': {
    id: 'panda-bao',
    ear: 'round',
    earColor: 'accent',
    tail: 'stub',
    headAccessory: 'none',
    snout: 'none',
    faceMarking: 'mask',
    appendage: 'none',
    palette: {
      body: '#FFFFFF',
      bodyDark: '#D8D3D8',
      belly: '#F7F5F7',
      accent: '#4A4550',
    },
  },
  'axolotl-bubi': {
    id: 'axolotl-bubi',
    ear: 'none',
    tail: 'paddle',
    headAccessory: 'gill-fronds',
    snout: 'none',
    faceMarking: 'none',
    appendage: 'none',
    palette: {
      body: '#FFC9DE',
      bodyDark: '#E092B3',
      belly: '#FFE6F0',
      accent: '#FF8FB8',
    },
  },
  'erizo-hoja': {
    id: 'erizo-hoja',
    ear: 'stubby',
    tail: 'stub',
    headAccessory: 'leaf-sprigs',
    snout: 'none',
    faceMarking: 'none',
    appendage: 'none',
    palette: {
      body: '#E3C9A8',
      bodyDark: '#B8916A',
      belly: '#F5E6D0',
      accent: '#8FC97A',
    },
  },
  'pinguino-copo': {
    id: 'pinguino-copo',
    ear: 'none',
    tail: 'stub',
    headAccessory: 'none',
    snout: 'beak-flat',
    faceMarking: 'none',
    appendage: 'flippers',
    palette: {
      body: '#3E4A6B',
      bodyDark: '#2B3450',
      belly: '#FFFFFF',
      accent: '#FFB84D',
    },
  },
  'dragoncito-chispa': {
    id: 'dragoncito-chispa',
    ear: 'stubby',
    tail: 'spade',
    headAccessory: 'dragon-horns',
    snout: 'none',
    faceMarking: 'none',
    appendage: 'wings',
    palette: {
      body: '#C9B8FF',
      bodyDark: '#9B84E0',
      belly: '#E6DBFF',
      accent: '#FFD86B',
    },
  },
}
